/** The Stage 1 demo workspace content (grows from docs/examples/slice-0). */
export const DEMO_FILES: Record<string, string> = {
  'index.md': [
    '---',
    'title: Tributary Demo',
    'kind: index',
    '---',
    '',
    '# Tributary Demo',
    '',
    'Welcome to the demo workspace. Links plus executable TSX cells.',
    '',
    '- [[notes/hello|Hello]]',
    '- [[notes/other|Other notes]]',
    '- [[items/task-1|Ship the demo]]',
    '- [[items/task-2|Write tests]]',
    '',
    '![[notes/hello]]',
    '',
    '\u0060\u0060\u0060js',
    'const greeting = "Tributary renders TSX cells here."',
    '\u0060\u0060\u0060',
    '',
    '\u0060\u0060\u0060tsx',
    '<strong>{greeting}</strong>',
    '\u0060\u0060\u0060',
    '',
    '\u0060\u0060\u0060js',
    'import { workItems } from "@tributary/api"',
    'const items = workItems()',
    '\u0060\u0060\u0060',
    '',
    '\u0060\u0060\u0060tsx',
    '<ul>{items.map((w) => <li>{w.title}</li>)}</ul>',
    '\u0060\u0060\u0060',
    '',
  ].join('\n'),
  'notes/hello.md': [
    '---',
    'title: Hello',
    'kind: wiki',
    '---',
    '',
    '# Hello',
    '',
    'A simple wiki document that links to a [[items/task-1|work item]].',
    '',
    '\u0060\u0060\u0060js source',
    '// A static snippet: "source" opts out of execution.',
    'const x = 1;',
    '\u0060\u0060\u0060',
    '',
    '\u0060\u0060\u0060js',
    '6 * 7',
    '\u0060\u0060\u0060',
    '',
  ].join('\n'),
  'notes/other.md': [
    '---',
    'title: Other notes',
    'kind: wiki',
    '---',
    '',
    '# Other notes',
    '',
    'A second wiki document, to give the link graph another edge.',
    '',
  ].join('\n'),
  'items/task-1.md': [
    '---',
    'id: task-1',
    'title: Ship the demo',
    'kind: work-item',
    'status: todo',
    'assignee: alice',
    'priority: high',
    'project: demo',
    '---',
    '',
    '# Ship the demo',
    '',
    'A work item is just a Markdown document with typed frontmatter.',
    '',
  ].join('\n'),
  'items/task-2.md': [
    '---',
    'id: task-2',
    'title: Write tests',
    'kind: work-item',
    'status: done',
    'assignee: bob',
    'priority: medium',
    'project: demo',
    '---',
    '',
    '# Write tests',
    '',
    'Another work item for the board projection.',
    '',
  ].join('\n'),
};