/** The Stage 1 demo workspace content (grows from docs/examples/slice-0). */
export const DEMO_FILES: Record<string, string> = {
  'index.md': [
    '---',
    'title: Tributary Demo',
    'type: index',
    '---',
    '',
    '# Tributary Demo',
    '',
    'Welcome to the demo workspace. Links plus executable TSX cells.',
    '',
    '- [[notes/hello|Hello]]',
    '- [[notes/other|Other notes]]',
    '- [[items/task-1|Ship the demo]]',
    '- [[items/task-2|Write tests]]',
    '- [[problems/runtime-flakiness|Runtime invalidation is flaky]]',
    '',
    '![[notes/hello]]',
    '',
    '\u0060\u0060\u0060js',
    'const greeting = "Tributary renders TSX cells here."',
    '\u0060\u0060\u0060',
    '',
    '\u0060\u0060\u0060tsx',
    '<strong>{greeting}</strong>',
    '\u0060\u0060\u0060',
    '',
    '\u0060\u0060\u0060js',
    'import { workItems } from "@tributary/api"',
    'const items = workItems()',
    '\u0060\u0060\u0060',
    '',
    '\u0060\u0060\u0060tsx',
    '<ul>{items.map((w) => <li>{w.title}</li>)}</ul>',
    '\u0060\u0060\u0060',
    '',
  ].join('\n'),
  'notes/hello.md': [
    '---',
    'title: Hello',
    'type: wiki',
    'aliases: [Greeting, Hello Doc]',
    'tags: [demo, wiki]',
    '---',
    '',
    '# Hello',
    '',
    'A simple wiki document that links to a [[items/task-1|work item]].',
    '',
    '\u0060\u0060\u0060js source',
    '// A static snippet: "source" opts out of execution.',
    'const x = 1;',
    '\u0060\u0060\u0060',
    '',
    '\u0060\u0060\u0060js',
    '6 * 7',
    '\u0060\u0060\u0060',
    '',
  ].join('\n'),
  'notes/other.md': [
    '---',
    'title: Other notes',
    'type: wiki',
    '---',
    '',
    '# Other notes',
    '',
    'A second wiki document, to give the link graph another edge.',
    '',
  ].join('\n'),
  'work/projects/demo.md': [
    '---',
    'id: project-demo',
    'title: Demo Project',
    'type: project',
    'aliases: [demo]',
    '---',
    '',
    '# Demo Project',
    '',
    'Work items reference this document by id, so renaming it keeps the board',
    'grouping intact (ADR-005).',
    '',
  ].join('\n'),
  'problems/runtime-flakiness.md': [
    '---',
    'id: problem-runtime-flakiness',
    'title: Runtime invalidation is flaky',
    'type: problem',
    'aliases: [flaky runtime]',
    '---',
    '',
    '# Runtime invalidation is flaky',
    '',
    'A problem document: work items reference it by id, so renaming the problem',
    'keeps the grouping intact (ADR-005).',
    '',
  ].join('\n'),
  'items/task-1.md': [
    '---',
    'id: task-1',
    'title: Ship the demo',
    'type: work-item',
    'status: doing',
    'assignees: [user:alice, user:carol]',
    'priority: 1',
    'project: project-demo',
    'problem: problem-runtime-flakiness',
    'labels: [demo, release]',
    'due: 2026-09-30',
    '---',
    '',
    '# Ship the demo',
    '',
    'A work item is just a Markdown document with typed frontmatter (ADR-005):',
    'a list of typed assignees, a numeric priority and a project reference that',
    'resolves to [[work/projects/demo|Demo Project]].',
    '',
  ].join('\n'),
  'items/task-2.md': [
    '---',
    'id: task-2',
    'title: Write tests',
    // Deliberately legacy: `kind`, a single `assignee` and a named priority.
    // The ontology reads all three, normalises them and reports diagnostics
    // rather than refusing the document (ADR-005 §9).
    'kind: work-item',
    'status: done',
    'assignee: bob',
    'priority: medium',
    'project: demo',
    '---',
    '',
    '# Write tests',
    '',
    'A deliberately old-style work item: the board shows it normalised, and the',
    'workspace reports the deprecated spellings as diagnostics.',
    '',
  ].join('\n'),
};